[build]
  publish = "web/build"
  command = "cd web && NODE_ENV=production yarn sass && react-scripts build && react-snap && yarn run generate-sw"

[context.production]
  [context.production.environment]
    NODE_VERSION       = "9.9.0"
    YARN_VERSION       = "1.5.1"
    NO_PDF             = "true"
    X_CLIENT_ID        = ""
    GOOGLE_PROJECT_ID  = ""
    GCE_USERNAME       = ""
    GCE_INSTANCE_NAME  = ""
    WAKATIME_API_KEY   = ""
    INSTAGRAM_USER     = ""
    INSTAGRAM_PASSWORD = ""
    SENDGRID_API_KEY   = ""
